src/components/SchemaRow.tsx
src/components/SchemaTree.tsx

fix: spacing

---

src/__fixtures__/tickets.schema.json
src/components/SchemaRow.tsx
src/utils/__tests__/__snapshots__/renderSchema.spec.ts.snap
src/utils/__tests__/renderSchema.spec.ts
src/utils/renderSchema.ts
src/utils/walk.ts

before:
after:
Besides displaying all properties with proper indentation, I also fixed the properties counter for arrays.

fix: handle array of objects properly [SL-2638]

---

src/components/SchemaRow.tsx
src/components/Types.tsx

 feat: dark theme improvements

---

src/components/SchemaRow.tsx
src/components/__tests__/SchemaRow.spec.tsx

Fixes https://github.com/stoplightio/json-schema-viewer/issues/30

fix: render falsy validation values

---

src/components/SchemaRow.tsx

This PR is a bugfix, that shows carets that expand objects/arrays.

fix: show "expand" caret

---

src/utils/renderSchema.ts

Related to [STU-362](https://stoplightio.atlassian.net/browse/STU-362)
Changes:
- fix issue causing not rendering schema if object node does not have a type specified
Context:
Issue appeared only for arrays that contained objects without specified type. This way node subtype property was undefined and the process of node children rendering stopped.  
Before:
After:

fix incorrect rendering of array of objects with no type [STU-362]

---

src/__stories__/JsonSchemaViewer.tsx
src/components/JsonSchemaViewer.tsx
src/components/SchemaRow.tsx
src/components/SchemaTree.tsx
src/components/__tests__/SchemaRow.spec.tsx
src/components/__tests__/Type.spec.tsx
src/components/index.tsx
src/components/shared/Caret.tsx
src/components/shared/Description.tsx
src/components/shared/Divider.tsx
src/components/shared/Property.tsx
src/components/shared/Types.tsx
src/components/shared/Validations.tsx
src/components/shared/index.ts
src/index.ts
src/types.ts
src/utils/renderSchema.ts

List of changes:
- working optional allOf merging
- rowRenderer instead of `rowRendererRight` (please refer to https://github.com/stoplightio/json-schema-viewer/pull/37#discussion_r302609270 for more details)
- cleanup
Needed to unyalc JSV in Studio.

feat: introduce rowRenderer 

---

package.json
src/components/JsonSchemaViewer.tsx
src/components/__tests__/JsonSchemaViewer.spec.tsx
web-worker-loader.d.ts
yarn.lock

Make sure to test it in the failing repo :laughing: 
Related: https://github.com/stoplightio/app-gen3/issues/351

feat: shim web worker

---

src/components/JsonSchemaViewer.tsx
src/components/__tests__/JsonSchemaViewer.spec.tsx
src/workers/messages.ts
src/workers/schema.ts

Fixes https://github.com/stoplightio/json-schema-viewer/issues/49

fix(rendering): uncaught exception

---

src/__fixtures__/array-of-allofs.json
src/components/JsonSchemaViewer.tsx
src/components/shared/Property.tsx
src/utils/__tests__/__snapshots__/renderSchema.spec.ts.snap
src/utils/__tests__/isCombiner.spec.ts
src/utils/__tests__/renderSchema.spec.ts
src/utils/getArraySubtype.ts
src/utils/getCombiner.ts
src/utils/isCombiner.ts
src/utils/isRef.ts
src/utils/isSchemaViewerEmpty.ts
src/utils/nodes.ts
src/utils/renderSchema.ts
src/utils/walk.ts

Fixes https://github.com/stoplightio/json-schema-viewer/issues/50 and perhaps https://github.com/stoplightio/json-schema-viewer/issues/44
Side note,
I need to make heavier use of tagged union types, so that we don't need to to these `as Something` explicit type assertions. This will result in much cleaner code - will do it at some point.

fix: combiners inside of arrays

---

src/__stories__/JsonSchemaViewer.tsx
src/components/JsonSchemaViewer.tsx
src/types.ts
src/utils/__tests__/flattenTypes.spec.ts
src/utils/__tests__/renderSchema.spec.ts
src/utils/flattenTypes.ts
src/utils/isValidType.ts
src/utils/walk.ts

Fixes https://github.com/stoplightio/studio-internal/issues/1041

fix: handle invalid types more gracefully

---

src/__fixtures__/default-schema.json
src/components/shared/Validations.tsx
src/utils/__tests__/__snapshots__/renderSchema.spec.ts.snap

- fixes an issue where the validations key is overlapping with the value
**Before**
**After**

fix: validations key overlaps value

---

src/utils/__tests__/__snapshots__/renderSchema.spec.ts.snap
src/utils/__tests__/renderSchema.spec.ts
src/utils/renderSchema.ts
src/utils/walk.ts

Fixes https://github.com/stoplightio/json-schema-viewer/issues/58
A note on snapshot change - it shouldn't have any impact, since the actual node that gets rendered in tree-list has a proper type assigned - see [line 146](https://github.com/stoplightio/json-schema-viewer/blob/b186ec373f0b3f00184f4171ce3412b4b5987cb2/src/utils/__tests__/__snapshots__/renderSchema.spec.ts.snap#L146) and [line 197](https://github.com/stoplightio/json-schema-viewer/blob/b186ec373f0b3f00184f4171ce3412b4b5987cb2/src/utils/__tests__/__snapshots__/renderSchema.spec.ts.snap#L197).
It's just that the other nodes point at original object.
You can also verify it manually in storybook by pasting the schema file and comparing the view. :P
This got me realize we actually seem to squeeze too much into metadata. It seems …

fix: do not mutate combiner child

---

src/components/__tests__/Property.spec.tsx
src/components/shared/Property.tsx
src/utils/guards.ts

Fixes https://github.com/stoplightio/studio-internal/issues/1608

fix: handle nullish items

---

src/utils/renderSchema.ts

Open to suggestions on better alternative. Current behavior is no good - if there is a `null` value the entire component doesn't work.
@P0lip thoughts?

fix: don’t kill entire JSV for one null value

---

src/components/__tests__/SchemaRow.spec.tsx
src/components/__tests__/Validations.spec.tsx
src/components/shared/Validations.tsx
src/utils/__tests__/getValidations.spec.ts
src/utils/getValidations.ts

Addresses https://github.com/stoplightio/platform-internal/issues/736
Before:
After:

feat: render deprecated next to general validations

---

src/components/shared/Validations.tsx

Now as `BigInt` numbers may be used we need to stringify them safely.
Though in case of validations we don't need to use stringify as we check for arrays and objects before. Unless there are other possible types that won't work well with `String()`). Are there @P0lip ?
We could just use `safeStringify` but then we won't get wrapping quotes for strings and would need to check for type anyway.

Fix: safe stringify

---

src/tree/__tests__/tree.spec.ts
src/tree/utils/populateTree.ts
src/tree/utils/walk.ts

Related to https://github.com/stoplightio/platform-internal/issues/3007
Resolving function may throw error which should be handled when resolving schema eagerly. 
Instead of replacing all children from parent node with an error one it should add proper child containing that error node.
**Before**:
**After**:

fix: eager resolving errors

---

src/__fixtures__/default-schema.json
src/__stories__/JsonSchemaViewer.tsx
src/components/JsonSchemaViewer.tsx
src/components/shared/Validations.tsx
src/tree/__tests__/tree.spec.ts
src/tree/tree.ts
src/types.ts

Addresses https://github.com/stoplightio/elements/issues/634
Adds render context that defines whether to render `readOnly` and `writeOnly` nodes (for OAS request/response schemas). 
Brings out `readOnly` and `writeOnly` validations (standalone schemas).

feat: conditionaly render readOnly writeOnly nodes

---

src/tree/__tests__/tree.spec.ts
src/utils/guards.ts

Unrelated minor issue I spotted while working on https://github.com/stoplightio/platform-internal/issues/4527
Before:
After:

fix: include subtypes for complex types that include array

---

src/__tests__/__snapshots__/index.spec.tsx.snap
src/components/__tests__/Format.spec.tsx
src/components/__tests__/Validations.spec.tsx
src/components/shared/Format.tsx
src/components/shared/Validations.tsx
src/components/shared/index.ts

Initially implemented in #91.
`span` felt more appropriate here.

refactor: move Format component out of Validations

---

src/__stories__/JsonSchemaViewer.tsx
src/__tests__/index.spec.tsx
src/components/JsonSchemaViewer.tsx
src/components/SchemaTree.tsx

This is breaking from a component's perspective, but not from ours - we usually set `expandedDepth` to 1 and do not use `expanded` anywhere.
Furthemore, migrated a few tests I added yesterday to the other branch.

feat: drop expanded prop

---

package.json
src/__fixtures__/default-schema.json
src/__tests__/__snapshots__/index.spec.tsx.snap
src/components/shared/Validations.tsx
src/components/shared/__tests__/Validations.spec.tsx
yarn.lock

Resolves https://github.com/stoplightio/elements/issues/668
Makes validations being displayed in more human friendly way.

feat: redesign validations

---

src/__stories__/JsonSchemaViewer.tsx
src/__tests__/__snapshots__/index.spec.tsx.snap
src/__tests__/index.spec.tsx
src/components/JsonSchemaViewer.tsx
src/components/SchemaRow.tsx
src/components/shared/Caret.tsx
src/components/shared/ChildStack.tsx
src/components/shared/Description.tsx
src/components/shared/Divider.tsx
src/components/shared/Format.tsx
src/components/shared/Properties.tsx
src/components/shared/Property.tsx
src/components/shared/Types.tsx
src/components/shared/Validations.tsx
src/components/shared/__tests__/Property.spec.tsx
yarn.lock

Times in parenthesis are mounting times of the 2x-stress schema story in Storybook.
- Bumps @stoplightio/json-schema-merge-allof (1660ms -> 1590ms)
- Removes trivial mosaic components from the performance-critical rendering paths: `SchemaRow` and beyond (1590ms -> 850ms)
The problem with mosaic components is that for almost 0 gain (beyond type-checking of style-props), you render yet another element, and especially yet another `forwardRef`-ed element, both of which eat up performance as you scale.

perf: improve performance

---

src/components/JsonSchemaViewer.tsx
src/components/shared/Property.tsx
src/tree/tree.ts

Addresses https://github.com/stoplightio/platform-internal/issues/5476
This is already fixed in beta, which uses entirely different code, but Studio cannot use v4 just yet, thus a dedicated change had to be applied.
FWIW, I'm glad we moved all the complexity away from JSV :sweat_smile: 
v3 is quite tangled at this point.

fix: readOnly/writeOnly not respected for >=2 levels

---

src/components/__tests__/Validations.spec.tsx
src/utils/__tests__/getValidations.spec.ts
src/utils/getValidations.ts

Addresses https://github.com/stoplightio/platform-internal/issues/4350
Initially I wanted to address this directly in `http-spec`, but I quickly changed my mind, as this could potentially break certain usages. These 5 formats are OAS-specific, and JSON Schema does not support them, therefore the conversion we do includes correct ranges, so that generic JSON Schema tooling can interpret such a schema correctly.
Unfortunately, as a side effect, the values get inserted to the document, and JSV renders them.
The solution I decided to go with is rather simple. Since a format implies the valid ranges, we do not need to show it unless a given value was overridden manually.
To be ported to JST / JSV v4.

feat: do not display min/max values for oas formats

---

src/__tests__/__snapshots__/index.spec.tsx.snap
src/tree/utils/walk.ts

Addresses https://github.com/stoplightio/platform-internal/issues/5799
I'm so happy this code is entirely gone in beta, and that JST has it done more reasonably :see_no_evil: 
`tickets.schema.json` has been updated due to that fix, see the portion of that whole schema document
```json
"ticketRecipients": {
"type": "array",
"items": {
"type": "string",
"enum": [
"BOOKER",
"CUSTOMER",
"PASSENGER",
"THIRD_PARTY"
]
}
},
```

fix: use items validation for flattened arrays

---

src/__stories__/JsonSchemaViewer.tsx
src/components/JsonSchemaViewer.tsx
src/components/SchemaRow/SchemaRow.tsx
src/components/shared/Validations.tsx
src/components/shared/__tests__/Validations.spec.tsx
src/contexts/jsvOptions.tsx

Fixes https://github.com/stoplightio/elements/issues/1026
Adds `hideExamples` property to JSV that prevents rendering example validations.

feat: hide examples option

---

package.json
src/components/JsonSchemaViewer.tsx
src/components/SchemaRow.tsx
src/components/SchemaTree.tsx
src/components/shared/Divider.tsx
src/components/shared/Types.tsx
src/components/shared/Validations.tsx
src/tree/__tests__/utils/printTree.ts
src/tree/metadata.ts
src/tree/tree.ts
src/tree/utils/__tests__/walk.spec.ts
src/tree/utils/canStepIn.ts
src/tree/utils/mergeAllOf.ts
src/tree/utils/mergeOneOrAnyOf.ts
src/tree/utils/populateTree.ts
src/tree/utils/walk.ts
src/types.ts
src/utils/flattenTypes.ts
src/utils/getAnnotations.ts
src/utils/getCombiners.ts
src/utils/getMetadata.ts
src/utils/getPrimaryType.ts
src/utils/getValidations.ts
src/utils/guards.ts
src/utils/inferType.ts
src/utils/isCombiner.ts
src/utils/isValidType.ts
yarn.lock

For https://github.com/stoplightio/platform-internal/pull/6083
This _does not_ add any meaningful support of new features introduced in Draft 6 & Draft 7. Everything's going to be processed in the same way as it used to be.

feat: accept JSON Schema Draft 6 & Draft 7

---

package.json
src/__tests__/__snapshots__/index.spec.tsx.snap
src/components/shared/Description.tsx
yarn.lock

A part of: https://github.com/stoplightio/elements/issues/1092
This one basically wraps the description content in `Markdown Viewer`

feat: add Markdown support in descriptions

---

package.json
yarn.lock

Bumps mdv and scripts to build ES module as `.esm.js` instead of `.ejs`.
Needed for webpack 4 example in https://github.com/stoplightio/elements/issues/957

fix: esm build

---

src/components/JsonSchemaViewer.tsx

Needed for https://github.com/stoplightio/platform-internal/pull/7139

feat: added onTreePopulated prop

---

src/__tests__/__snapshots__/index.spec.tsx.snap
src/components/shared/Validations.tsx
src/components/shared/__tests__/Validations.spec.tsx

Addresses: https://github.com/stoplightio/platform-internal/issues/7377
Quotes were added to distinguish the type of validation. 
This PR makes `enum`, `examples` and `default` not show quotes regardless of type.

feat: do not wrap string validations

---

src/__tests__/__snapshots__/index.spec.tsx.snap
src/components/shared/Validations.tsx
src/components/shared/__tests__/Validations.spec.tsx

For stoplightio/elements#1665
I believe the issue occurs because type: array node is not recursively processed like object type so enum property was never found. This fixes the issue described in the ticket but it also changed the jest snapshot for a schema defined in `src/__fixtures__/tickets.schema.json` and indeed, found enums that should be included for a property like this:
```json
"availableDeliveryTypes": {
"type": "array",
"items": {
"type": "string",
"enum": [
"POSTAL",
"PICK_UP_STATION",
"E-MAIL",
"LOYALTY_CARD"
]
}
}
```

fix: check for array child enum

---

src/__tests__/__snapshots__/index.spec.tsx.snap
src/components/SchemaRow/SchemaRow.tsx
src/components/SchemaRow/TopLevelSchemaRow.tsx

Addresses https://github.com/stoplightio/platform-internal/issues/7717
Top level:
Row level:

Add more UI feedback when JSON schema uses anyOf or oneOf

---

README.md

https://github.com/stoplightio/json-schema-viewer/pull/170 was supposed to get released automatically but apparently I didn't include the correct magic word ("fix") so it didn't. 😭 
Second time is a charm. 🤞

fix(ui): make small change to actually release my previous ui changes

---

src/__tests__/__snapshots__/index.spec.tsx.snap
src/components/shared/Validations.tsx

For stoplightio/platform-internal#9043
I couldn't find the reason why `NameValidations` were used for boolean types so I removed it 🤷‍♂️ 
Now, in case of
```json
"defaultExample1": {
"type": "boolean",
"default": true
},
"defaultExample2": {
"type": "boolean",
"default": false
}
```
It shows:
Rather than displaying `Default` in case `default: true` and nothing in case of `default: false`.
Besides that, I noticed it also fixed the issue with some other boolean types like:
```json
"something": {
"type": "boolean",
"example": true
}
```
Which is was previously displayed as:
@mallachari Do you remember why was `NameValidations` needed for booleans? Is there some cases that i'm not seeing which this PR could broke?

fix: removed NameValidations to properly show default values

---

src/__stories__/JsonSchemaViewer.tsx
src/__stories__/_styles.scss
src/hooks/useIsOnScreen.ts

E.g. the one in legacy ui-kit that is used in Studio.

fix: path crumbs compat with virtual scroll containers

---

src/components/SchemaRow/SchemaRow.tsx
src/components/SchemaRow/TopLevelSchemaRow.tsx
src/components/__tests__/SchemaRow.spec.tsx
src/components/__tests__/TopLevelSchemaRow.spec.tsx
src/components/shared/Validations.tsx

When users are viewing public endpoints that reference internally marked schemas, we need a way to display an error message to let the user know they do not have permissions to view it.
#InsertIssueNumberHere
https://github.com/stoplightio/platform-internal/issues/10534
Added a check at the toplevelschemarow and at the schemarow levels to check for the `x-sl-error-message` property
Manually tested changes by pulling this package into platform internal and manually making changes to the schema and schema permissions and seeing if the error message showed up as expected.
Added test coverage for SchemaRow

feat(error-check): add check for  error message

---

src/components/SchemaRow/SchemaRow.tsx

fix: only re-render divider on hover

---

src/__tests__/__snapshots__/index.spec.tsx.snap
src/__tests__/index.spec.tsx
src/components/JsonSchemaViewer.tsx
src/components/SchemaRow/TopLevelSchemaRow.tsx

Discussed with @P0lip on slack.
Follow-up to https://github.com/stoplightio/json-schema-viewer/pull/205 that adds a `skipTopLevelDescription` prop so that users can opt into old behavior (not rendering top level description).
We need this for standalone schema docs pages in elements.

feat: add skipTopLevelDescription option

---

src/__tests__/index.spec.tsx
src/components/SchemaRow/SchemaRow.tsx
src/components/SchemaRow/TopLevelSchemaRow.tsx
src/components/__tests__/SchemaRow.spec.tsx
src/components/__tests__/TopLevelSchemaRow.spec.tsx
src/components/shared/Error.tsx
src/components/shared/Validations.tsx
src/utils/getInternalSchemaError.ts

https://github.com/stoplightio/platform-internal/issues/16994
I added Tooltip, fixed the color, and changed the placement a little bit.
Plus, now that we use `x-stoplight`, I made `getInternalSchemaError` look at `x-stoplight.error-message`
Before:
After:

feat: show internal schema errors in a nicer way

---

src/__tests__/__snapshots__/index.spec.tsx.snap
src/components/shared/Description.tsx

Add `data-test` for descriptions

fix: add data-test attribute for descriptions

---

src/__fixtures__/combiners/oneof-with-allof-children.json
src/components/SchemaRow/SchemaRow.tsx
src/components/SchemaRow/TopLevelSchemaRow.tsx
src/components/SchemaRow/index.ts
src/components/SchemaRow/useChoices.ts
src/index.ts
src/tree/utils.ts

https://github.com/stoplightio/platform-internal/issues/18370
json-schema-viewer and TryIt have been using different logic to determine if/how to display form-encoded schemas that have a `oneOf` combiner at the top level.
Expose a few utility features for use by related, downstream tools that also render JSON Schema in one way or another. 
Specifically, the TryIt function of Elements will be able to reuse the same logic -- and thereby get the same visible results -- as json-schema-viewer.
Existing functionality is being exported; no functional changes were made.

export useChoices and other utilities for elements

---

package.json
src/__fixtures__/references/allOfReference.json
src/__fixtures__/references/fullAllOfReference.json
src/__stories__/Refs.tsx
src/utils/refResolver.ts
yarn.lock

https://github.com/stoplightio/elements/issues/2419
A reference within an allOf that had description or summary ref siblings were getting overwritten by description and summary from the referenced object. 
Bump json-schema-tree version that has fix that does not allow reference description and summary to overwrite the ref sibling's values
Added ref resolver for storybook so that the references are actually resolved for storybook
Added storybook that shows the allOf reference example
Before version bump:
After version bump:

fix(package.json): bump json-schema-tree version

---

src/__fixtures__/default-schema.json
src/components/__tests__/SchemaRow.spec.tsx
src/utils/getApplicableFormats.ts

[STOP-464
](https://smartbear.atlassian.net/browse/STOP-464)
Format is handled for contentMediaType type i.e. binary format
Tested in local environment.

fix: <binary> is not displaying in the docs

---

src/components/shared/Validations.tsx
src/components/shared/__tests__/Validations.spec.tsx

[STOP-231](https://smartbear.atlassian.net/browse/STOP-231)
Previously range was getting displayed without being defined in the schema for int64.
Tested locally by doing yalc in Platform internal.
Before
After 
[STOP-231]: https://smartbear.atlassian.net/browse/STOP-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Don't display int64 range in docs
