stoplightio/json-schema-viewer

__mocks__/react.ts
package.json
setupTests.ts
src/__mocks__/theme.ts
src/__tests__/JsonSchemaViewer.spec.tsx
src/__tests__/SchemaView.spec.tsx
src/renderers/__fixtures__/all-of.json
src/renderers/__fixtures__/nested-properties.json
src/renderers/__fixtures__/properties.json
src/renderers/__tests__/__snapshots__/renderSchema.func.tsx.snap
src/renderers/__tests__/renderSchema.func.tsx
src/util/__tests__/isCombiner.spec.ts
src/util/__tests__/isSchemaViewerEmpty.spec.ts
src/util/isSchemaViewerEmpty.ts
yarn.lock

[SL-1223] tests

---

package.json
src/renderers/__tests__/__snapshots__/renderSchema.func.tsx.snap
src/renderers/renderProp.tsx

Icon size no longer supported with 
https://github.com/stoplightio/ui-kit/pull/93

style(icon): change icon size to fontsize

---

__mocks__/styleMock.js
jest.config.js
package.json
src/common/ErrorMessage.tsx
src/renderers/__tests__/__snapshots__/renderSchema.func.tsx.snap
src/renderers/renderProp.tsx
src/renderers/renderRowDivider.tsx
yarn.lock

Will need to update ui-kit dep once stoplightio/ui-kit#97 is merged

chore(spacing): update spacing values

---

package.json
src/__fixtures__/default-schema.json
src/utils/__tests__/__snapshots__/renderSchema.spec.ts.snap
src/utils/getValidations.ts
tslint.json
yarn.lock

Add additional validation types to common list

fix: update common validations

---

src/index.ts
src/utils/index.ts

Changes:
- exports `renderSchema` and `mergeAllOf`.

feat: export utils functions

---

package.json
src/__stories__/worker.shim.ts
src/components/SchemaRow.tsx
src/components/SchemaTree.tsx
src/components/__tests__/SchemaRow.spec.tsx
src/components/shared/Property.tsx
yarn.lock

Going to be needed by [feat/new-tree-list](https://github.com/stoplightio/json-schema-viewer/tree/feat/new-tree-list)

chore: bump TypeScript

---

src/components/SchemaRow.tsx
src/components/shared/Property.tsx
src/components/shared/Types.tsx
src/tree/__tests__/populateTree.spec.ts
src/tree/__tests__/tree.spec.ts
src/tree/tree.ts
src/tree/utils/populateTree.ts
src/utils/guards.ts

Fixes https://github.com/stoplightio/json-schema-viewer/issues/71
Changes:
- arrays containing ref items can be resolved and expanded

fix: array local refs

---

src/__stories__/JsonSchemaViewer.tsx
src/__stories__/_styles.scss
src/components/__tests__/Property.spec.tsx
src/components/__tests__/Type.spec.tsx
src/components/shared/Property.tsx
src/components/shared/Types.tsx
src/tree/__tests__/tree.spec.ts
src/tree/utils/__tests__/walk.spec.ts
src/tree/utils/populateTree.ts
src/tree/utils/walk.ts
src/types.ts
src/utils/getAnnotations.ts

General rules:
- given object type & present title, we enrich the type with name, i.e.
```json
{
"title": "User",
"type": "object",
"properties": {
"name": {
"type": "string"
}
}
}
```
Before:
After:
- given array type with non-array items, we replace the subtype name with title, i.e.
```json
{
"type": "array",
"items": {
"title": "User",
"type": "object",
"properties": {
"name": {
"type": "string"
}
}
}
}
```
Before:
After:
- given array type with no items
```json
{
"type": "array",
"title": "Foo"
}
```
Before:
After:
- $refs - we try to retrieve the title from referenced property
```json
{
"type": "object",
"properties": {
"foo": {
"$ref": "#/properties/user"
},
"user" : {
"title": "User",
"properties": {
"name": {
"type": "string"
}
}
}
}
}
```
Before (eager resolving enabled):
Before …

feat: consume schema title property

---

package.json
src/components/__tests__/Property.spec.tsx
src/components/shared/Property.tsx
src/tree/__tests__/__snapshots__/tree.spec.ts.snap
src/tree/__tests__/tree.spec.ts
src/tree/__tests__/utils/printTree.ts
src/tree/utils/__tests__/walk.spec.ts
src/tree/utils/canStepIn.ts
src/tree/utils/mergeOneOrAnyOf.ts
src/tree/utils/populateTree.ts
src/tree/utils/walk.ts
src/utils/getCombiner.ts
src/utils/getCombiners.ts
yarn.lock

Closes https://github.com/stoplightio/platform-internal/issues/4440

feat: support multiple combiners

---

src/components/__tests__/Validations.spec.tsx
src/components/shared/Validations.tsx

Relates to https://github.com/stoplightio/elements/issues/655

feat: remove optional tag

---

src/tree/__tests__/tree.spec.ts
src/tree/utils/mergeAllOf.ts

Fixes https://github.com/stoplightio/platform-internal/issues/4411

fix: all of circular references may freeze

---

src/__fixtures__/allof-with-type.json
src/__fixtures__/oneof-with-array-type.json
src/__tests__/__snapshots__/index.spec.tsx.snap
src/__tests__/index.spec.tsx
src/tree/__tests__/__snapshots__/tree.spec.ts.snap
src/tree/__tests__/populateTree.spec.ts
src/tree/__tests__/tree.spec.ts
src/tree/__tests__/utils/printTree.ts
src/tree/utils/mergeOneOrAnyOf.ts
src/tree/utils/populateTree.ts
src/tree/utils/walk.ts

Requires https://github.com/stoplightio/json-schema-viewer/pull/86
Closes_ https://github.com/stoplightio/platform-internal/issues/4382

feat: better support of anyOf/oneOf + type scenario

---

package.json
yarn.lock

Extracted to make #110 smaller
Brings all the goodness of the latest mosaic release here!

chore: bump mosaic

---

.github/CODEOWNERS

As agreed, we move JSV into a shared state of ownership between VC and Undefined

chore(codeowners): add undefined to CODEOWNERS

---

package.json
src/__fixtures__/references/nested.json
src/__tests__/__snapshots__/index.spec.tsx.snap
yarn.lock

Relates to https://github.com/stoplightio/elements/issues/1006

fix: handling nested schemas with allof

---

package.json
src/__fixtures__/combiners/oneof-within-array-item.json
src/__tests__/__snapshots__/index.spec.tsx.snap
src/components/SchemaRow/useChoices.ts
src/utils/printName.ts
yarn.lock

Resolves #125 
Depends on https://github.com/stoplightio/json-schema-tree/pull/11

feat: better names for oneOf/anyOf selector

---

package.json
yarn.lock

Relates to https://github.com/stoplightio/elements/issues/1519

fix: elements docs crashing in cra example

---

package.json
src/components/JsonSchemaViewer.tsx
yarn.lock

Incorporates https://github.com/stoplightio/react-error-boundary/pull/6

fix(deps): upgrade @stoplight/react-error-boundary to v2

---

package.json
yarn.lock

Needed for https://github.com/stoplightio/platform-internal/issues/8463
Bumps `json-schema-tree`

fix: merge allof titles

---

src/__stories__/index.ts

Addresses :
https://github.com/stoplightio/json-schema-viewer/pull/176#discussion_r756423027
Removed unnecessary import from Storybook

fix(json-schema-viewer): removed unnecessary import

---

package.json
yarn.lock

Addresses https://github.com/stoplightio/elements/issues/2136
Bumps json-schema-tree version

fix(package.json): bump json-schema-tree version

---

src/__tests__/__snapshots__/index.spec.tsx.snap
src/__tests__/index.spec.tsx
src/components/SchemaRow/SchemaRow.tsx
src/components/shared/Description.tsx
src/components/shared/Format.tsx
src/components/shared/Properties.tsx
src/components/shared/Types.tsx
src/components/shared/Validations.tsx
src/components/shared/__tests__/Property.spec.tsx

Adds `data-test` attributes to the schema viewer to make testing easier
Added `data-test` attributes to mirror the schema-editor
Updated tests, all passing

feat(adding data-test attributes): add data-test attributes

---

src/__fixtures__/arrays/of-complex-objects.json
src/components/SchemaRow/TopLevelSchemaRow.tsx

Needed for: https://github.com/stoplightio/platform-internal/issues/17424
Adds displaying validations for the top level of complex arrays.

feat: array top level validations

---

src/components/SchemaRow/TopLevelSchemaRow.tsx

Fixes top level array validations

fix: top level array validations

---

package.json
src/components/JsonSchemaViewer.tsx
yarn.lock

upgrade json-schema-tree and pass the new option around

feat: pass maxRefDepth to tree to limit recursion

---

src/components/shared/Validations.tsx
src/components/shared/__tests__/Validations.spec.tsx

[#12705](https://app.zenhub.com/workspaces/-team-honey-hackers-62ab7d6627416c001df37493/issues/gh/stoplightio/platform-internal/12705)
Shows pattern match for array with subtype string
Before
After

fix: array child pattern match validation

---

package.json
yarn.lock

#STOP-1012
A vulnerability was detected within the json-schema-viewer project through the inclusion of the semver dependency.
Semver is internally used by @size-limit/preset-big-lib this package. to resolve this dependency we updated @size-limit/preset-big-lib package.
1. Locally tested , test cases , build and code also running and working properly
2. Yalc the change into platform-internal and tested

STOP-1012(Bump): semver version updated for security issues

---

package.json
yarn.lock

[#STOP-1096](https://smartbear.atlassian.net/jira/software/c/projects/STOP/boards/2033?assignee=712020%3Ae7af16c3-6282-4504-8e21-2ee8d0ac31f2&selectedIssue=STOP-1096)
I have upgraded the rollup version from 4.18.0 to 4.22.4 as per the requirement.
I have tested locally. I have tried build, lint, test, test.prod, test.update command all are executed successfully.

chore(deps): bump rollup version from from 2.47.0 to 4.22.4

---

package.json
yarn.lock

[STOP-849](https://smartbear.atlassian.net/browse/STOP-849)
bump "webpack-dev-middleware" package to 7.1.0
This is devdependency used to to build and test. I have tested the changes by executing the build, test, test.prod, test.update, lint, lint.fix commands. All the mentioned command executed successfully.
[STOP-849]: https://smartbear.atlassian.net/browse/STOP-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bump: webpack-dev-middleware package to 7.1.0

---

package.json
yarn.lock

[STOP-844](https://smartbear.atlassian.net/browse/STOP-844)
A vulnerability was detected within the json-schema-viewer project through the inclusion of the braces-None dependency.
Tested locally by executing the build, test, test.prod, test.update, lint, lint.fix commands. All commands executed successfully. Also tested this changes using yalc on elements and platform-internal
[STOP-844]: https://smartbear.atlassian.net/browse/STOP-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(deps): bump @storybook/core from 6.5.0 to 8.3.6

---

package.json
yarn.lock

[STOP-847](https://smartbear.atlassian.net/browse/STOP-847)
A vulnerability was detected within the json-schema-viewer project through the inclusion of the trim-none dependency.
Tested locally by executing the build, test, test.prod, test.update, lint, lint.fix commands. All commands executed successfully.
[STOP-847]: https://smartbear.atlassian.net/browse/STOP-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(deps): bump trim to 0.0.3

---

package.json
yarn.lock

[STOP-848](https://smartbear.atlassian.net/browse/STOP-848)
A vulnerability was detected within the json-schema-viewer project through the inclusion of the trim-newlines-none dependency.
Tested locally by executing the build, test, test.prod, test.update, lint, lint.fix commands. All commands executed successfully.
yarn build 
yarn test
yarn lint 
[STOP-848]: https://smartbear.atlassian.net/browse/STOP-848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(deps): bump trim-newlines to 3.0.1

---

package.json
yarn.lock

[STOP-1279](https://smartbear.atlassian.net/browse/STOP-1279)
To resolve the security issue, I have upgraded cross-spawn version to 7.0.5
This package is a Dev Dependency , therefore I tested it by running the commands yarn build, yarn test, and yarn lint.
[STOP-1279]: https://smartbear.atlassian.net/browse/STOP-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(deps): bump cross-spawn 7.0.5

---

src/components/JsonSchemaViewer.tsx
src/components/SchemaRow/SchemaRow.tsx
src/components/SchemaRow/TopLevelSchemaRow.tsx

[STOP-95](https://smartbear.atlassian.net/browse/STOP-95)
Handled Description for Combiners (OneOf/AllOf/AnyOf)
have tested by yalc testing on Platform-internal.
[STOP-95]: https://smartbear.atlassian.net/browse/STOP-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Handling description for Combiners-STOP-95

---

package.json
yarn.lock

[STOP-1957](https://smartbear.atlassian.net/browse/STOP-1957)
[STOP-1510](https://smartbear.atlassian.net/browse/STOP-1510)
[STOP-1700](https://smartbear.atlassian.net/browse/STOP-1700)
Bump up vite,path-to-regexp& nanoid packages
Have tested by running commands **yarn build, yarn lint & yarn test**
[STOP-1957]: https://smartbear.atlassian.net/browse/STOP-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[STOP-1510]: https://smartbear.atlassian.net/browse/STOP-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[STOP-1700]: https://smartbear.atlassian.net/browse/STOP-1700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(deps): Bump up vite,path-to-regexp& nanoid packages
